@extends('mix::layouts.master')
@section('title', __('Two-Factor Authentication'))

@section('content')
<div class="mix-padding-10">
    <div class="dashboard-header-banner relative mt-0 mb-10">
        <div class="card-container">
            <div class="text-lg font-bold">{{ __('Two-Factor Authentication') }}</div>
            <div class="side-cta">
                <img src="{{ gs('assets/image/emoji/Yellow-1/Shield.png') }}" onerror="this.src='{{ gs('assets/image/emoji/Yellow-1/Nerdy.png') }}'" alt="">
            </div>
        </div>
    </div>
    
    <div class="card-container bg-white rounded-lg shadow-sm p-6">
        @if($user->google2fa_enabled)
            <!-- Enabled State -->
            <div class="text-center max-w-md mx-auto">
                <div class="text-green-500 mb-4 flex justify-center">
                     <svg class="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                </div>
                <h3 class="text-xl font-bold mb-2">{{ __('2FA is Enabled') }}</h3>
                <p class="text-gray-600 mb-6">{{ __('Your account is secured with Two-Factor Authentication.') }}</p>
                
                <hr class="my-6 border-gray-100">
                
                <div class="bg-red-50 p-4 rounded-lg border border-red-100">
                    <h4 class="font-bold mb-4 text-red-500 text-left">{{ __('Disable 2FA') }}</h4>
                    <form action="{{ route('user-mix-account-security-disable') }}" method="POST">
                        @csrf
                        <div class="mb-4 text-left">
                            <label class="block text-gray-700 text-sm font-bold mb-2">{{ __('Current Password') }}</label>
                            <input type="password" name="current-password" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-red-500" required>
                        </div>
                        <button type="submit" class="w-full bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded-lg transition duration-200">
                            {{ __('Disable 2FA') }}
                        </button>
                    </form>
                </div>
            </div>
        @else
            <!-- Disabled State -->
            <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div>
                    <h3 class="text-xl font-bold mb-4">{{ __('Setup 2FA') }}</h3>
                    <div class="space-y-4">
                        <div class="flex items-start">
                            <span class="flex-shrink-0 w-6 h-6 bg-blue-100 text-blue-500 rounded-full flex items-center justify-center font-bold text-sm mr-3">1</span>
                            <p>{{ __('Install Google Authenticator (or any TOTP app) on your phone.') }}</p>
                        </div>
                        <div class="flex items-start">
                            <span class="flex-shrink-0 w-6 h-6 bg-blue-100 text-blue-500 rounded-full flex items-center justify-center font-bold text-sm mr-3">2</span>
                            <p>{{ __('Scan the QR Code below with the app.') }}</p>
                        </div>
                    </div>
                    
                    <div class="mt-6 mb-4 flex flex-col items-center bg-gray-50 p-6 rounded-lg border border-gray-200">
                         @if(isset($QR_Url))
                            {!! QrCode::size(200)->generate($QR_Url) !!}
                         @endif
                         <div class="mt-4 text-center">
                             <p class="text-xs text-gray-500 mb-1">{{ __('Unable to scan?') }}</p>
                             <p class="text-sm font-mono bg-white px-2 py-1 rounded border">{{ $secret }}</p>
                         </div>
                    </div>
                </div>
                
                <div class="flex flex-col justify-center">
                     <div class="bg-blue-50 p-6 rounded-lg border border-blue-100">
                         <div class="flex items-start mb-6">
                            <span class="flex-shrink-0 w-6 h-6 bg-blue-500 text-white rounded-full flex items-center justify-center font-bold text-sm mr-3">3</span>
                            <h3 class="font-bold text-lg">{{ __('Verify & Enable') }}</h3>
                        </div>
                         
                         <p class="mb-4 text-sm text-gray-600 ml-9">{{ __('Enter the 6-digit code generated by the app to verify and enable 2FA.') }}</p>
                         
                         <form action="{{ route('user-mix-account-security-enable') }}" method="POST" class="ml-9">
                            @csrf
                            <div class="mb-4">
                                <label class="block text-gray-700 text-sm font-bold mb-2">{{ __('Verification Code') }}</label>
                                <input type="text" name="verify-code" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-center tracking-widest text-xl" placeholder="000 000" required>
                            </div>
                            <button type="submit" class="w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded-lg transition duration-200 shadow-lg">
                                {{ __('Enable 2FA') }}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        @endif
    </div>
</div>
@endsection
